udp: listen: Add reuse_address and reuse_port options
lemunozm/message-io pull request #146
Opened 2023-03-17 14:31 UTC by kgraefe

This change requires all UDP sockets (not just multicast sockets) to be created by socket2::Socket as mio::net::UdpSocket does not provide the set_reuse_address and set_reuse_port functions.

2023-03-17 14:33 UTC, kgraefe commented
Sorry for spamming PRs ;-) it's just that I converted the adjustments I had hard-coded in my local fork onto the new API.

2023-03-21 08:25 UTC, lemunozm requested changes
Two comments, but I really like how the new implementation looks! 🚀

2023-03-21 08:25 UTC, lemunozm commented on src/adapters/udp.rs
> +        }
Why not:

```rust
socket.set_reuse_address(config.reuse_address)?;
```

Is to avoid overwriting a value that it already is?

2023-03-22 07:19 UTC, lemunozm approved these changes
Thanks for this second iteration. Very neat PRs!

2023-03-22 07:19 UTC, merged